### ISSUE TITLE
OTP Field missing from login page (yubikey plugin)

### ISSUE THREAD

**Issue by theemstra** [aaroniker/imscp-next#2]
For users of the paid Yubikey plugin, the OTP field is missing.

The YubiKey plugin attempts to inject the extra field in to the index.tpl, but it's not able to, because the index.tpl doesn't have the same structure.

This would need to be added below the password field, if the yubikey plugin is enabled, then you can login with Yubikey OTP just fine.

```
<div class="form-element">
        <label for="yubikey_otp">{TR_YUBIKEY_OTP}</label>
        <input type="text" class="form-field" name="yubikey_otp" id="yubikey_otp" value="">
    </div>
```

**Comment by nuxwin** [comment]
@theemstra 

You need adapt the plugin which inject the html at runtime. This problem should be pointed on our bugtracker, not here ;)

**Comment by theemstra** [comment]
Hi @nuxwin 

As per your request I've created: http://youtrack.i-mscp.net/issue/IP-1841
